### PR TITLE
Project QOL and org changes

### LINKED ISSUE #2: Settle on core lang
We need to settle the core project setup. Our top candidates are Django in Python and Golang (maybe with a framework like gin)

Discussion of pros and cons. We may do an ARD later https://adr.github.io/

### PR DESCRIPTION
**Pull request by CharlesDLandau**
I'm working on a collection of changes to pave the way for easier development. .gitignore, issue templates, automation, go conventions, licensing, documentation, etc.

### CODE REVIEW

**Comment by CharlesDLandau** [comment]
Since `inbound=outbound` (see [this section of a very opinionated writeup](https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/#if-a-license-isnt-good-enough-for-maintainers-you-shouldnt-subject-users-to-it) for more) I think we can forego a CLA

**Comment by CharlesDLandau** [comment]
Because we are using go, I'm hoping we can avoid having a dedicated docker directory to begin with. I'm definitely open to having it, but I like the idea of keeping it a simple golang dev environment, with containers only coming in for CI/CD.

[Remove docker folder](https://github.com/tatrasproject/tatras/pull/1/commits/b8f9528e798944cc1c9cbd84b1f6b8f4370cee85)

**Comment by jharmon96** [comment]
Holding off until we settle the Python vs Go situation

**Comment by CharlesDLandau** [comment]
> Holding off until we settle the Python vs Go situation

I'm going to continue working on this because I miss go. Interested in your analysis once you've had a chance

**Review by CharlesDLandau — COMMENTED** [review]
I looked it over and it's ready for your review @jharmon96 . Once this merges we can start building out the gin app

**Review by jharmon96 — APPROVED** [review]

**Pull request merged**
